### ISSUE TITLE
[VoB] genuki direct links broken

### ISSUE THREAD

**Issue by michaelstoner** [gbhgis/issues#1]
Broken links as Emailed in by Chris P, thanks Chris.

> Your Page: http://www.visionofbritain.org.uk/place/11493/links, Link: 
> http://www.genuki.org.uk/big/eng/WIL/Ansty/index.html
> - Chris P

There appears to be a problem with the genuki direct links for Wiltshire parishes as they have changed the genuki urls - just had a look at this from user query...

this is what we currently have:
http://www.genuki.org.uk/big/eng/WIL/Ansty/index.html
This is now the actual page:
http://www.genuki.org.uk/big/eng/WIL/Ansty/index.shtml

Tried Bishops Cannings with same results.

**Comment by HumphreySouthall** [comment]
I have fixed this, if the only issue is with Wiltshire. Ran this:

vob=> update hgis.g_link set g_url = replace(g_url, 'index.html', 'index.shtml') where g_authority='GENUKI_WEB' and g_url like 'http://www.genuki.org.uk/big/eng/WIL/%';

The Ansty example now works. NB GENUKI is a very strange "site", based on lots of static HTML pages hosted on various servers; you can usually treat pages for a given county as a block, but not the whole thing.

**Comment by paulavob** [comment]
It is fixed for parishes with a single word for a name e.g. Averbury or Ansty. However I just checked and any parishes where there is more than one word in the name e.g. "bishops cannings" or "donhead st mary" have not been updated and still have the same error.

e.g.
current link is http://www.genuki.org.uk/big/eng/WIL/DonheadStMary/index.htm
correct link should be http://www.genuki.org.uk/big/eng/WIL/DonheadStMary/index.shtml

Thanks
