### ISSUE TITLE
Boundaries for admin units not showing up in VoB - pink wash on entire screen

### ISSUE THREAD

**Issue by paulavob** [gbhgis/issues#2]
Email from user Philip Hunt

"While I find Gillingham, Dorset CP/AP in your indexes and then bring up the boundary map, it displays and then, nigh on immediately, gets covered with a slightly opaque pink wash, which makes the map more or less useless and I certainly cannot see the boundary.
I am using Mozilla Firefox version 35.0.1 under Windows 8.1."

Thanks Philip. This is a problem for everywhere so either I did something wrong when I was uploading boundary shape files into db yesterday, but I'm pretty sure I set it so files only related to gbhdb or it was something you did Michael. Can you look into please?

**Comment by HumphreySouthall** [comment]
Loading shape files into the GBHDB schema could not possibly have done this — only changes to hgis.g_foot could have any effect on what appears on that page. and I don’t think even changes there could have this effect

Must be an issue introduced with the most recent update to the code, so one for Michael

H

**Comment by michaelstoner** [comment]
## Looking Into this now

Michael.

**Comment by michaelstoner** [comment]
Fixed, a knock on effect of a mistake I made yesterday with the permissions on accessing the database.
